%run_all.m
% Student Name: Sharvan Saikumar
% Student ID: 33918236
% Date: 13/10/2024

clear all; close all; clc;
%% Do not edit this file in any way. Your demonstrator will run this file
% and it should print all values and produce all plots required for the
% assignment.  

% It runs each part individually.
% There should be no intervention from the user.
% Students will lose marks if this file does not run properly.

%% Q1
Q1;

%% Q2
Q2;

%% Q3
Q3;

%% Q4
Q4;

%% Q5
Q5;